apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      serviceAccountName: todo-sa
      containers:
        - name: web
          image: alpine:3.19
          command: ["sh","-c","sleep infinity"]
          # Порт тут не критичний; головне — pod живий для exec
          ports:
            - containerPort: 8080
